# Generated by Django 4.1 on 2022-11-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orientador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orientador',
            old_name='first_name',
            new_name='Primeiro_none',
        ),
        migrations.RenameField(
            model_name='orientador',
            old_name='last_name',
            new_name='Ultimo_nome',
        ),
    ]
