# Generated by Django 4.1 on 2022-11-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orientador', '0002_rename_first_name_orientador_primeiro_none_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orientador',
            old_name='Primeiro_none',
            new_name='Primeiro_nome',
        ),
    ]
