# Generated by Django 4.1 on 2022-08-23 15:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft_nome', models.CharField(max_length=200)),
                ('ult_nome', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft_nome', models.CharField(max_length=200)),
                ('ult_nome', models.CharField(max_length=200)),
                ('link_curriculo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('orientador', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('ano_doc', models.DateField(verbose_name='Ano documento')),
                ('arquivo_doc', models.FileField(upload_to='docs')),
                ('palavras_chave', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
    ]
